### ISSUE TITLE
Lightning fire does not extinguish until player get nearby

### ISSUE THREAD

**Issue by xeranas** [minetest-mods/lightning#1]
Lightning creates fire far away but extinguish it only when player is nearby. This could lead to unwanted results e.g. after thunderstorm all around player base are visible fire until he walks around.

**Comment by sofar** [comment]
The chance that the lightning mod places a spreading fire is only 1 in a million.

**Comment by sofar** [comment]
Actually, I misread this comment.

Yes, the nodes are nodetimer based and they won't disappear until you come in range (usually 20-30 nodes from the node).

Doing it in another way would be difficult and problematic.
