### ISSUE TITLE
Make fire and default optional dependencies

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/lightning#7]
In order to make this mod more flexible and easier to include in random subgames, I suggest this:

* Make default dependency optional. If this mod is not present, the node conversion code is simply skipped
* Make the fire dependency optional. If this mod is not present, lightnings simply don't spawn fires.

**Comment by sofar** [comment]
d426c60, 0f15757

**Comment by Wuzzy2** [comment]
Great! Thanks. :-)
